### PR TITLE
Added SignUp with Gitlab

### PR DESCRIPTION
**Pull request by LeiHao0**
Hi, this is the SignupWithGitlab commit I issued earlier to Add.

Now It can be sign up with gitlab all fine, but all `Realm` object works wrong if log out.

I'm not sure what's going. Whether user logined controlled by `Webview` cookies, so after this gitlab step the rest should be the same.

Am I messed something?

### CODE REVIEW

**Comment by Mehdzor** [comment]
@ivedeneev Can you test an issue with logout?

**Comment by ivedeneev** [comment]
@Mehdzor sure

**Comment by ivedeneev** [comment]
@Artwalk sry for delay, we will give u feedback few days later. Can u describe what exactly goes wrong with realm?

**Comment by LeiHao0** [comment]
It crashed at line  485 in `ChatViewController` when Logout
```swift
guard !self.channel.isInvalidated else { return }
```

After rerun the project, the crash point is at line 184 in LeftMenuViewController`

```swift
guard self.resultsPublic.count > 0 else { return }
```

I `po self.resultsPublic` and found it is nil

`Commit 5d84c55`

By the way, my Team do not have the `general` channel, does these relevant?

**Comment by Mehdzor** [comment]
@Artwalk When user data is corrupted repeatable crashes may occur. We'll investigate into the issue and write back very soon. Thank you for your effort!

**Comment by LeiHao0** [comment]
yep, after rebase `6dda4d9`, it crashed only at 1137 line in `ChatViewController`
`navigationTitleView.configureWithChannel(channel: channel)`

furthermore, the log
`Mattermost[27263:172285] Socket did disconnect`

repeating again and again until I killed the app

**Comment by LeiHao0** [comment]
The repeating `Socket did disconnect` caused by server side which returned 500

**Comment by Mehdzor** [comment]
@Artwalk Did you find out what the error is about?

**Comment by Jufina** [comment]
@Artwalk Hi! I would personally get to your pull request at the next monday. We're releasing the app into the AppStore and there are a lot of bugs need to be fixed.

**Comment by LeiHao0** [comment]
@Mehdzor the `v3/users/websocket` connection get `url:port` from server somehow ( it should be url only ), it's ok now after our DevOps changed a config flag of the server side.

@Jufina Oh, Will you keep open-sourcing this project?
By the way, I found the archived app ("-Owholemodule") will crash when authorize in the gitlab webView, the breakpoint is pointing at a realm object which based on `fec704c`. 
It did not happened in `Debug Scheme` which `SWIFT_OPTIMIZATION_LEVEL` is "-Onone" or "-O".

And, [In Mattermost 3.5, It can use a token rather than cookies](http://forum.mattermost.org/t/websocket-routing-error/2607)

**Comment by Mehdzor** [comment]
@Artwalk fixed the crash already, ty for reporting. 

Yea, we keep open source as long as Mattermost itself is open source.

**Comment by Mehdzor** [comment]
@Artwalk Do you mind making more pull requests? We might use some help with the project.

**Comment by LeiHao0** [comment]
@Mehdzor no problem if I find something may useful.

**Comment by LeiHao0** [comment]
Sorry that I forgot clear webView Cookies

```
     func resetCookie() {
-        guard isSignedIn() else { return }
+        guard isSignedIn() else {
+            // gitlab, it's hard to specify webView cookies cache, so I simply remove all
+            HTTPCookieStorage.shared.cookies?.forEach {
+                HTTPCookieStorage.shared.deleteCookie($0)
+            }
+            return
+        }
```

**Pull request closed without merging**
